import type { Language, Question } from "@/types";

type EnglishQuestion = { question: string; options: string[] };
const item = (question: string, options: string[]): EnglishQuestion => ({ question, options });

const englishQuestions: Record<string, EnglishQuestion[]> = {
  Geography: [
    item("What is the capital of Georgia?", ["Batumi", "Tbilisi", "Kutaisi", "Rustavi"]),
    item("What is the largest continent in the world?", ["Africa", "Europe", "Asia", "Australia"]),
    item("On which continent is the Nile River located?", ["Asia", "Africa", "Europe", "South America"]),
    item("What is the capital of France?", ["Paris", "Lyon", "Marseille", "Nice"]),
    item("In which mountain range is Mount Everest?", ["The Alps", "The Caucasus", "The Himalayas", "The Andes"]),
    item("Which country is shaped like a boot?", ["Greece", "Italy", "Spain", "Portugal"]),
    item("What is the largest ocean in the world?", ["Atlantic", "Indian", "Arctic", "Pacific"]),
    item("What is the capital of Japan?", ["Tokyo", "Kyoto", "Osaka", "Nagoya"]),
    item("Which sea borders Georgia to the west?", ["Mediterranean Sea", "Caspian Sea", "Black Sea", "Red Sea"]),
    item("On which continent is Brazil located?", ["North America", "South America", "Africa", "Asia"]),
  ],
  Science: [
    item("What is the chemical formula for water?", ["H2O", "CO2", "O2", "NaCl"]),
    item("Which planet is called the Red Planet?", ["Venus", "Mars", "Jupiter", "Mercury"]),
    item("What is the largest organ in the human body?", ["Liver", "Heart", "Skin", "Lung"]),
    item("Which gas do plants absorb during photosynthesis?", ["Oxygen", "Hydrogen", "Nitrogen", "Carbon dioxide"]),
    item("At what temperature does water boil at sea level?", ["0°C", "50°C", "100°C", "150°C"]),
    item("What is the hardest natural substance?", ["Iron", "Diamond", "Gold", "Quartz"]),
    item("Approximately how fast does light travel in a vacuum?", ["300,000 km/s", "30,000 km/s", "3,000 km/s", "300 km/s"]),
    item("Which planet is especially famous for its rings?", ["Mars", "Neptune", "Saturn", "Earth"]),
    item("What does DNA carry?", ["Genetic information", "Thermal energy", "Sound waves", "Electrical charge"]),
    item("What is the unit of force?", ["Watt", "Joule", "Pascal", "Newton"]),
  ],
  History: [
    item("Who was the first king of a unified Georgia?", ["David IV", "Bagrat III", "George V", "Vakhtang VI"]),
    item("Whose reign is associated with Georgia's Golden Age?", ["Erekle II", "Vakhtang Gorgasali", "Queen Tamar", "Pharnavaz I"]),
    item("In which year did World War II end?", ["1939", "1941", "1944", "1945"]),
    item("Which civilization built the Pyramids of Giza?", ["Ancient Egyptians", "Romans", "Maya", "Greeks"]),
    item("In which country was Magna Carta signed?", ["France", "England", "Spain", "Italy"]),
    item("In which year did Christopher Columbus reach the Americas?", ["1453", "1490", "1492", "1500"]),
    item("Who is considered the first Roman emperor?", ["Augustus", "Nero", "Julius Caesar", "Trajan"]),
    item("In which year did the French Revolution begin?", ["1776", "1789", "1812", "1848"]),
    item("Who developed the printing press in Europe?", ["Galileo", "Newton", "Da Vinci", "Johannes Gutenberg"]),
    item("In which year did the Berlin Wall fall?", ["1979", "1985", "1989", "1991"]),
  ],
  Technology: [
    item("What does HTML stand for?", ["HyperText Markup Language", "HighText Machine Language", "Hyper Transfer Main Language", "Home Tool Markup Language"]),
    item("What is CSS used for?", ["Managing databases", "Styling web pages", "Managing servers", "Compressing files"]),
    item("Who created JavaScript?", ["Tim Berners-Lee", "James Gosling", "Brendan Eich", "Dennis Ritchie"]),
    item("How many bits are in one byte?", ["4", "8", "16", "32"]),
    item("Which is a document-oriented database?", ["PostgreSQL", "MySQL", "SQLite", "MongoDB"]),
    item("What does HTTP stand for?", ["HyperText Transfer Protocol", "High Transfer Text Process", "Home Tool Transfer Protocol", "Hyper Terminal Track Program"]),
    item("What is Git used for?", ["Editing images", "Sending email", "Version control", "Editing video"]),
    item("What does CPU stand for?", ["Computer Personal Unit", "Central Processing Unit", "Control Program Utility", "Central Power User"]),
    item("Which company created React?", ["Google", "Microsoft", "Apple", "Facebook (Meta)"]),
    item("What is the encrypted version of HTTP?", ["HTTPS", "HTTPC", "SHTTPX", "FTP"]),
  ],
  Sports: [
    item("How many players from one football team are on the field?", ["9", "10", "11", "12"]),
    item("How many points is a basketball free throw worth?", ["1", "2", "3", "4"]),
    item("How often are the Summer Olympic Games normally held?", ["Every 2 years", "Every 4 years", "Every 5 years", "Every 6 years"]),
    item("In which sport is Wimbledon held?", ["Golf", "Rugby", "Tennis", "Cricket"]),
    item("Which country won the 2022 FIFA World Cup?", ["France", "Brazil", "Germany", "Argentina"]),
    item("Which sport does the NBA represent?", ["Basketball", "Baseball", "Hockey", "American football"]),
    item("What is the official marathon distance?", ["21.1 km", "40 km", "42.195 km", "50 km"]),
    item("How many pieces does each player start with in chess?", ["12", "16", "18", "20"]),
    item("Which sport uses an oval ball?", ["Tennis", "Basketball", "Hockey", "Rugby"]),
    item("How many players from one volleyball team are on court?", ["6", "7", "8", "9"]),
  ],
  Literature: [
    item("Who wrote The Knight in the Panther's Skin?", ["Ilia Chavchavadze", "Shota Rustaveli", "Akaki Tsereteli", "Vazha-Pshavela"]),
    item("Who wrote Hamlet?", ["William Shakespeare", "Charles Dickens", "Victor Hugo", "Mark Twain"]),
    item("Who is the author of the novel 1984?", ["Aldous Huxley", "Ray Bradbury", "George Orwell", "Ernest Hemingway"]),
    item("Who wrote Don Quixote?", ["Dante Alighieri", "Gabriel García Márquez", "Lewis Carroll", "Miguel de Cervantes"]),
    item("Who is the author of The Little Prince?", ["Jules Verne", "Antoine de Saint-Exupéry", "Alexandre Dumas", "Honoré de Balzac"]),
    item("Who is traditionally credited with writing The Odyssey?", ["Homer", "Sophocles", "Plato", "Aristotle"]),
    item("Who wrote Pride and Prejudice?", ["Emily Brontë", "Virginia Woolf", "Jane Austen", "Agatha Christie"]),
    item("Who is the author of War and Peace?", ["Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev", "Leo Tolstoy"]),
    item("Who wrote The Metamorphosis?", ["Albert Camus", "Franz Kafka", "Hermann Hesse", "Thomas Mann"]),
    item("Who wrote the Harry Potter books?", ["J. K. Rowling", "Suzanne Collins", "Stephenie Meyer", "Philip Pullman"]),
  ],
  Cinema: [
    item("Who directed Titanic?", ["Steven Spielberg", "Ridley Scott", "James Cameron", "Christopher Nolan"]),
    item("In which country are the Academy Awards presented?", ["France", "United States", "Italy", "Canada"]),
    item("Who directed The Godfather?", ["Francis Ford Coppola", "Martin Scorsese", "Stanley Kubrick", "Quentin Tarantino"]),
    item("Which actor plays Neo in The Matrix?", ["Tom Cruise", "Brad Pitt", "Matt Damon", "Keanu Reeves"]),
    item("Whose books inspired The Lord of the Rings?", ["George R. R. Martin", "C. S. Lewis", "J. R. R. Tolkien", "Terry Pratchett"]),
    item("Which studio created Toy Story?", ["Pixar", "DreamWorks", "Studio Ghibli", "Illumination"]),
    item("Which country produced the film Parasite?", ["Japan", "South Korea", "China", "Thailand"]),
    item("Who created Star Wars?", ["Peter Jackson", "James Cameron", "Steven Spielberg", "George Lucas"]),
    item("Which actor became one of the main icons of silent cinema?", ["Marlon Brando", "Humphrey Bogart", "Charlie Chaplin", "Clint Eastwood"]),
    item("Who plays Harry Potter in the films?", ["Daniel Radcliffe", "Rupert Grint", "Tom Felton", "Robert Pattinson"]),
  ],
  Music: [
    item("How many keys does a standard piano have?", ["76", "88", "92", "100"]),
    item("Which country was Ludwig van Beethoven from?", ["Germany", "Italy", "France", "Spain"]),
    item("Who composed The Four Seasons?", ["Mozart", "Bach", "Vivaldi", "Chopin"]),
    item("Who is known as the King of Pop?", ["Elvis Presley", "Freddie Mercury", "Prince", "Michael Jackson"]),
    item("In which city were The Beatles formed?", ["London", "Liverpool", "Manchester", "Birmingham"]),
    item("Which musical tradition does Georgian polyphony represent?", ["Polyphonic singing", "Opera", "Jazz", "Electronic music"]),
    item("How many strings does a standard violin have?", ["2", "3", "4", "6"]),
    item("Who was the lead singer of Queen?", ["Bono", "Mick Jagger", "Robert Plant", "Freddie Mercury"]),
    item("In which city was Wolfgang Amadeus Mozart born?", ["Vienna", "Salzburg", "Berlin", "Prague"]),
    item("Which award is associated with the music industry?", ["Grammy", "Oscar", "Emmy", "Pulitzer"]),
  ],
  Mathematics: [
    item("What is 7 × 8?", ["48", "54", "56", "64"]),
    item("What is the square root of 81?", ["8", "9", "10", "12"]),
    item("What is the sum of a triangle's interior angles?", ["180°", "270°", "360°", "90°"]),
    item("What is the approximate value of π?", ["1.41", "2.71", "4.13", "3.14"]),
    item("Which is a prime number?", ["9", "15", "17", "21"]),
    item("What is 25% of 200?", ["25", "50", "75", "100"]),
    item("What is 12²?", ["144", "124", "132", "164"]),
    item("How many sides does a pentagon have?", ["3", "4", "6", "5"]),
    item("If 2x + 6 = 14, what is x?", ["2", "3", "4", "5"]),
    item("Which number does the Roman numeral X represent?", ["5", "10", "50", "100"]),
  ],
  "General Knowledge": [
    item("How many days are in a leap year?", ["364", "365", "366", "367"]),
    item("What is the largest mammal in the world?", ["Blue whale", "African elephant", "Giraffe", "Hippopotamus"]),
    item("Who painted the Mona Lisa?", ["Michelangelo", "Leonardo da Vinci", "Raphael", "Pablo Picasso"]),
    item("In which country did an early form of chess originate?", ["China", "Egypt", "India", "Greece"]),
    item("What is the currency of Japan?", ["Won", "Yuan", "Dollar", "Yen"]),
    item("How many colors are traditionally identified in a rainbow?", ["6", "7", "8", "9"]),
    item("What is the capital of Canada?", ["Ottawa", "Toronto", "Vancouver", "Montreal"]),
    item("What is the fastest land animal?", ["Lion", "Antelope", "Leopard", "Cheetah"]),
    item("Which language is mainly spoken in Brazil?", ["Spanish", "English", "Portuguese", "French"]),
    item("What is Earth's natural satellite called?", ["Moon", "Sun", "Mars", "Venus"]),
  ],
};

export function localizeQuestion(topic: string, index: number, question: Question, language: Language): Question {
  if (language !== "en") return question;
  const translated = englishQuestions[topic]?.[index];
  return translated ? { ...question, ...translated } : question;
}
